/* eslint-env node */
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Defaults (output DIRECTORY by default)
// Keep only Material Symbols paths; drop any Material Icons (legacy) references
const DEFAULT_OUTPUT = path.resolve(
  __dirname,
  '../../src/shared/icons/symbols'
);
const METADATA_URL =
  'https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true';

// Status bitmask
const REMOVED = 0b100;
const UPDATED = 0b010;
const ADDED = 0b001;

// --- Small utils ---
const sortMap = (obj) =>
  Object.fromEntries(Object.entries(obj).sort((a, b) => a[0].localeCompare(b[0])));

async function get(url) {
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`GET ${url} failed: ${res.status} ${res.statusText} ${text}`);
  }
  return await res.text();
}

// --- Core logic (adapted from provided snippet) ---
export async function getMetadata() {
  let data = await get(METADATA_URL);
  // The API returns a non-JSON first line (XSSI prefix) – strip it
  data = data.substring(data.indexOf('\n'));
  return JSON.parse(data);
}

export async function getVersions() {
  // Only Material Symbols are supported
  const type = 'symbols';
  const { icons } = await getMetadata();
  const versions = {};
  icons.forEach((icon) => {
    for (const family of icon.unsupported_families) {
      if (String(family).toLowerCase().includes(type)) {
        return; // skip this icon
      }
    }
    versions[icon.name] = icon.version;
  });
  return sortMap(versions);
}

function getChanges(existing, latest) {
  existing = sortMap(existing);
  latest = sortMap(latest);
  const removed = [];
  const updated = [];
  const added = [];
  for (const name of Object.keys(existing)) {
    if (!latest[name]) {
      removed.push(name);
    } else if (latest[name] !== existing[name]) {
      updated.push(name);
    }
  }
  for (const name of Object.keys(latest)) {
    if (!existing[name]) {
      added.push(name);
    }
  }
  return { removed, updated, added };
}

function formatNames(list) {
  return list.map((n) => '`' + n + '`').join(', ');
}

async function checkChanges(file, latest) {
  let existing;
  try {
    const raw = await fs.readFile(file, 'utf8');
    existing = JSON.parse(raw);
  } catch (e) {
    if (e && e.code !== 'ENOENT') {
      console.error(e.message);
    }
    return ADDED; // treat as all added on first run
  }

  let status = 0;
  const { removed, updated, added } = getChanges(existing, latest);
  if (removed.length === 0 && updated.length === 0 && added.length === 0) {
    console.log('No changes');
    return status;
  }
  console.log('Changes:');
  if (removed.length !== 0) {
    console.log(`- Remove ${removed.length} icons: ${formatNames(removed)}`);
    status |= REMOVED;
  }
  if (updated.length !== 0) {
    console.log(`- Update ${updated.length} icons`);
    status |= UPDATED;
  }
  if (added.length !== 0) {
    console.log(`- Add ${added.length} icons: ${formatNames(added)}`);
    status |= ADDED;
  }
  return status;
}

export async function downloadVersions(outPath, dryRun = false) {
  // Allow passing either a directory or a file path. If a directory, append versions.json
  const file = outPath.endsWith('.json')
    ? path.resolve(outPath)
    : path.resolve(outPath, 'versions.json');
  console.log(`Downloading ${path.relative('', file)}`);
  const versions = await getVersions();
  const status = await checkChanges(file, versions);
  if (!dryRun) {
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, JSON.stringify(versions, null, 2));
    // Generate a TypeScript type file exporting all possible icon names
    const dtsPath = path.resolve(path.dirname(file), 'icons.d.ts');
    const names = Object.keys(versions);
    const union = names.map((n) => `'${n.replace(/'/g, "\\'")}'`).join(' | ');
    const banner = `// This file is auto-generated by tools/material-symbols/versions.mjs\n` +
      `// Do not edit manually.\n`;
    const content = `${banner}export type MaterialSymbolIcon = ${union};\n`;
    await fs.writeFile(dtsPath, content);
  }
  console.log('Done');
  return status;
}

// --- CLI ---
function parseArgs(argv) {
  const args = { out: DEFAULT_OUTPUT, dryRun: false };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--help' || a === '-h') args.help = true;
    else if (a === '--dry-run') args.dryRun = true;
    else if (a.startsWith('--out=')) args.out = a.slice(6);
    else if (a === '--out') {
      const v = argv[i + 1];
      if (!v || v.startsWith('--')) throw new Error('--out requires a value');
      args.out = v;
      i++;
    }
  }
  return args;
}

function printHelp() {
  console.log(`Material Symbols versions CLI\n\n` +
    `Usage: node versions.mjs [--dry-run] [--out <dir|file>]\n\n` +
    `Options:\n` +
    `  --dry-run        Do not write file; only show changes\n` +
    `  --out <dir|file> Output directory or file path for versions.json (also generates icons.d.ts)\n` +
    `                   (default directory: ${DEFAULT_OUTPUT})\n`);
}

if (import.meta.url === `file://${__filename}`) {
  (async () => {
    try {
      const args = parseArgs(process.argv);
      if (args.help) {
        printHelp();
        return;
      }
      const outPath = path.resolve(args.out);
      const status = await downloadVersions(outPath, args.dryRun);
      // Set exit code to bitmask for CI checks if needed
      if (status !== 0) process.exitCode = status;
    } catch (e) {
      console.error(e.stack || e.message || String(e));
      process.exitCode = 1;
    }
  })();
}

export const STATUS = { REMOVED, UPDATED, ADDED };
