import fs from 'node:fs/promises';
import type { PluginContext } from 'rollup';

export interface MetaOptions {
    strict?: boolean;
}

async function exists(p: string) {
    try {
        await fs.access(p);
        return true;
    } catch {
        return false;
    }
}

export async function fetchVersions(ctx: PluginContext, versionsFile: string, iconsTsFile: string, options: MetaOptions) {
    // Only fetch if file missing
    if (await exists(versionsFile)) return;

    ctx.info('[material-symbols-svg] Fetching Material Symbols metadata...');
    // Use the correct Material Symbols metadata endpoint; strip XSSI prefix
    const metaUrl = 'https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true';
    try {
        const res = await fetch(metaUrl);
        if (!res.ok) {
            const msg = `Failed to fetch metadata: HTTP ${res.status}`;
            if (options.strict) ctx.error(`[material-symbols-svg] ${msg}`); else ctx.warn(`[material-symbols-svg] ${msg}`);
            return;
        }

        let txt = await res.text();
        // The response starts with an XSSI guard like ")]}'" followed by a newline; remove the first line
        if (txt.startsWith(')]}\'')) {
            const i = txt.indexOf('\n');
            if (i !== -1) txt = txt.substring(i + 1);
        }

        // Transform to { [iconName]: version } like versions.mjs does, filtering out non-symbols
        let parsed: any;
        try {
            parsed = JSON.parse(txt);
        } catch (e) {
            const msg = 'Failed to parse metadata JSON';
            if (options.strict) ctx.error(`[material-symbols-svg] ${msg}`); else ctx.warn(`[material-symbols-svg] ${msg}`);
            parsed = null;
        }

        if (parsed && Array.isArray(parsed.icons)) {
            const versions: Record<string, string | number> = {};
            for (const icon of parsed.icons) {
                const famsAny = (icon && (icon as any)['unsupported_families']) as any;
                const families: any[] = Array.isArray(famsAny) ? famsAny : [];
                let skip = false;
                for (const fam of families) {
                    if (String(fam).toLowerCase().includes('symbols')) {
                        skip = true;
                        break;
                    }
                }
                if (skip) continue;
                const name = String((icon as any)?.name || '');
                if (!name) continue;
                versions[name] = (icon as any)?.version;
            }
            // Sort map by key
            const sorted = Object.fromEntries(Object.entries(versions).sort((a, b) => a[0].localeCompare(b[0])));
            const versionsContent = JSON.stringify(sorted, null, 2);

            await fs.writeFile(versionsFile, versionsContent);

            // Generate icons.ts with union of names (from metadata)
            try {
                const names = Object.keys(sorted);
                const union = names
                    .map((n) => `'${n.replace(/'/g, '\\\'')}'`)
                    .join(' | ');
                const banner = `// This file is auto-generated by vite-plugin-material-symbols-svg\n// Do not edit manually.\n`;
                const content = `${banner}export type MaterialSymbolIcon = ${union};\n`;

                let existing = '';
                try {
                    existing = await fs.readFile(iconsTsFile, 'utf-8');
                } catch {
                    // ignore
                }

                if (existing !== content) {
                    await fs.writeFile(iconsTsFile, content);
                    const now = new Date();
                    await fs.utimes(iconsTsFile, now, now).catch(() => { });
                }
            } catch (e) {
                // non-fatal
                const msg = e instanceof Error ? e.message : String(e);
                ctx.warn(`[material-symbols-svg] Failed to write icons.ts: ${msg}`);
            }
        } else {
            // Fallback: save cleaned JSON for inspection
            await fs.writeFile(versionsFile, txt);
        }
    } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        if (options.strict) ctx.error(`[material-symbols-svg] Metadata prefetch failed: ${msg}`); else ctx.warn(`[material-symbols-svg] Metadata prefetch failed: ${msg}`);
    }
}
