import fs from 'node:fs/promises';
import type { PluginContext } from 'rollup';
import { toFilename } from './symbols';

export type Theme = 'rounded' | 'outlined' | 'sharp';

export interface IconsInput {
    Symbols: Record<string, {
        sizes?: readonly number[];
        weights?: readonly number[];
        fills?: readonly (boolean | 0 | 1)[];
        themes?: readonly Theme[]
    }>;
    Custom?: Record<string, any>;
    Default?: any;
}

export function unique<T>(arr: T[]): T[] {
    return Array.from(new Set(arr));
}

export function normalizeNums(input: readonly unknown[] | undefined, fallback: readonly number[]): number[] {
    const src = input && input.length ? input : fallback;
    return unique(Array.from(src as readonly unknown[])
        .map((n) => Number(n))
        .filter((n) => Number.isFinite(n))) as number[];
}

export function normalizeFills(input: readonly (boolean | 0 | 1)[] | undefined, fallback: readonly (0 | 1)[]): (0 | 1)[] {
    const src = input && input.length ? input : fallback;
    const arr = Array.from(src).map((v) => {
        if (v === true) return 1;
        if (v === false) return 0;
        const n = Number(v);
        return n === 1 ? 1 : 0;
    }) as (0 | 1)[];
    return unique(arr) as (0 | 1)[];
}

export function normalizeThemes(input: readonly unknown[] | undefined, fallback: readonly Theme[]): Theme[] {
    const src = input && input.length ? input : fallback;
    const allowed: Theme[] = ['rounded', 'outlined', 'sharp'];
    const arr = Array.from(src as readonly unknown[])
        .map((t) => String(t) as Theme)
        .filter((t): t is Theme => allowed.includes(t));
    return unique(arr);
}

export const IconDefaultConfig = {
    sizes: [20, 24, 40, 48] as const,
    weights: [400] as const,
    fills: [0] as const,
    themes: ['rounded'] as const,
};

export async function generateConsumerFiles(
    ctx: PluginContext,
    iconsDef: IconsInput,
    loaderTypesFile: string,
    loaderMapFile: string,
    distDir: string,
) {
    const banner = `// This file is auto-generated by vite-plugin-material-symbols-svg\n// Do not edit manually.\n`;

    // 1. Generate loader-types.ts (IconKey)
    try {
        const symKeys = Object.keys(iconsDef.Symbols || {});
        const customKeys = Object.keys(iconsDef.Custom || {});
        const all = Array.from(new Set([...symKeys, ...customKeys]));
        const keyUnion = all.length
            ? all.map((n) => `'${n.replace(/'/g, '\\\'')}'`).join(' | ')
            : 'string';
        const typeContent = `${banner}export type IconKey = ${keyUnion};\n`;

        await fs.mkdir(distDir, { recursive: true });

        let existing = '';
        try {
            existing = await fs.readFile(loaderTypesFile, 'utf-8');
        } catch { }

        if (existing !== typeContent) {
            await fs.writeFile(loaderTypesFile, typeContent);
            const now = new Date();
            await fs.utimes(loaderTypesFile, now, now).catch(() => { });
        }
    } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        ctx.warn(`[material-symbols-svg] Failed to write loader-types.ts: ${msg}`);
    }

    // 2. Generate loader-map.ts
    try {
        const imports: string[] = [];
        const mapEntries: string[] = [];
        const defaults = iconsDef.Default ?? {};

        let i = 0;
        for (const [icon, meta] of Object.entries(iconsDef.Symbols || {})) {
            const sizes = normalizeNums((meta.sizes ?? defaults.sizes), IconDefaultConfig.sizes);
            const weights = normalizeNums((meta.weights ?? defaults.weights), IconDefaultConfig.weights);
            const fills = normalizeFills((meta.fills ?? defaults.fills), IconDefaultConfig.fills);
            const themes = normalizeThemes((meta.themes ?? defaults.themes), IconDefaultConfig.themes);

            for (const theme of unique(themes)) {
                for (const weight of unique(weights)) {
                    for (const fill of unique(fills)) {
                        for (const size of unique(sizes)) {
                            const filename = toFilename(icon, fill as 0 | 1, weight, size);
                            const importPath = `/symbols/${theme}/${filename}?raw`;
                            const varName = `i${i++}`;
                            imports.push(`import ${varName} from '${importPath}';`);
                            mapEntries.push(`  '${theme}::${icon}::${fill}::${weight}::${size}': ${varName},`);
                        }
                    }
                }
            }
        }

        // Add custom icons to the map if they are relative paths
        for (const [icon, sizesObj] of Object.entries(iconsDef.Custom || {})) {
            for (const [sizeKey, value] of Object.entries(sizesObj as any || {})) {
                if (typeof value === 'string' && (value.startsWith('./') || value.startsWith('../'))) {
                    const varName = `i${i++}`;
                    imports.push(`import ${varName} from '${value}?raw';`);
                    mapEntries.push(`  'rounded::${icon}::0::200::${sizeKey}': ${varName},`);
                }
            }
        }

        const mapContent = `${banner}${imports.join('\n')}\n\nexport default {\n${mapEntries.join('\n')}\n};\n`;

        let existing = '';
        try {
            existing = await fs.readFile(loaderMapFile, 'utf-8');
        } catch { }

        if (existing !== mapContent) {
            await fs.writeFile(loaderMapFile, mapContent);
            const now = new Date();
            await fs.utimes(loaderMapFile, now, now).catch(() => { });
        }
    } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        ctx.warn(`[material-symbols-svg] Failed to write loader-map.ts: ${msg}`);
    }
}
